version: "3.7"
services:
    postgresql:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - 5434:5432
      volumes:
        - .:/var/www/html
        - postgres_data:/var/lib/postgresql/data

    redis:
      image: redis:alpine
      expose:
        - 6379

    mailhog:
      image: mailhog/mailhog
      ports: 
        - 1025:1025
        - 8025:8025

    web:
      build: ./resources/docker/aws
      ports:
        - 8081:80
      volumes:
        - .:/var/www/html
      links:
        - php

    php:
      build: ./resources/docker/php
      ports:
        - 9000
      volumes:
        - .:/var/www/html
      links:
        - redis
        - postgresql
        - mailhog
      depends_on:
        - redis
        - postgresql
        - mailhog

volumes:
    postgres_data: